# Generated by Django 3.1.7 on 2021-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20210414_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetcode',
            name='check_link',
            field=models.BooleanField(default=False),
        ),
    ]
