# Generated by Django 3.1.7 on 2021-04-15 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_userresetcode_check_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 3, 13, 58, 742002)),
            preserve_default=False,
        ),
    ]
