# Generated by Django 3.1.7 on 2021-03-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
