# Generated by Django 3.1.7 on 2021-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210331_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='free_sample',
            field=models.BooleanField(default=False),
        ),
    ]
